version: "3.9"
services:
  angular-hot-reload:
    build:
      context: ./angular-hot-reload-example
      dockerfile: Dockerfile
      target: development
    image: clipbook/angular-app-hot-reload:V1
    container_name: angular-hot-reload
    command: ng serve --host 0.0.0.0
    ports:
      - '4200:4200'
    volumes:
      - /Users/ebinezer/personal-projects/angular-hotreload/angular-hot-reload-example:/app
      - /app/node_modules


  backend-service:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    image: clipbook/backend-app-hot-reload:V1
    container_name: backend-app
    command: npm run start:local
    ports:
      - '3500:8080'
    volumes:
      - /Users/ebinezer/personal-projects/angular-hotreload/backend-app:/app
      - /app/node_modules