version: "3.9"
services:
  angular-hot-reload:
    build:
      context: ./angular-hot-reload-example
      dockerfile: Dockerfile
    image: clipbook/angular-app-hot-reload-prod:V1
    container_name: angular-hot-reload
    ports:
      - '4200:80'


  backend-service:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    image: clipbook/backend-app-hot-reload:V1
    container_name: backend-app
    command: npm run start:local
    ports:
      - '3500:8080'