version: "3.9"
services:
  angular-hot-reload:
    build:
      context: ./angular-hot-reload-example
      dockerfile: Dockerfile
      target: development
    image: clipbook/angular-app-hot-reload:V1
    container_name: angular-hot-reload
    command: ng serve --host 0.0.0.0
    working_dir: /app
    ports:
      - '4200:4200'
    volumes:
      - /Users/ebinezer/personal-projects/angular-hotreload/angular-hot-reload-example:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: my-angular-nginx
    volumes:
      - ./angular-hot-reload-example/nginx-config-local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - angular-hot-reload


  backend-app:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    image: clipbook/backend-app-hot-reload:V1
    container_name: backend-app
    command: npm run start:local
    ports:
      - '3500:8080'
    volumes:
      - /Users/ebinezer/personal-projects/angular-hotreload/backend-app:/app
      - /app/node_modules