apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      name: angular-app
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: clipbook/angular-app-hot-reload:V7
          imagePullPolicy: Always
      restartPolicy: Always
